Make the development environment as close as possible to production
- Remove development manifests
- Remove specific pillar substitutions
- Point to the manifests using CONTAINER_MANIFESTS_DIR envvar along
  with the start script
- Script that takes production manifests and does the required changes
  and substitutions to convert them to development manifests

diff --git a/kubernetes/start b/kubernetes/start
--- a/kubernetes/start
+++ b/kubernetes/start
@@ -32,33 +32,36 @@ done
 
 ./cleanup
 
-default_interface=$(awk '$2 == 00000000 { print $1 }' /proc/net/route)
-ip_address=$(ip addr show $default_interface | awk '$1 == "inet" {print $2}' | cut -f1 -d/)
-
 # Use SALT_DIR is set and not empty else use our default directory
-# This can be used to point to different state files for orchestration.
+# This will be used to point to the state files for orchestration.
 if [ -z ${SALT_DIR+x} ]
 then
     log "You must provide a SALT_DIR, aborting"
     exit 1
-else
-    salt_dir=$SALT_DIR
 fi
+
+# Use CONTAINER_MANIFESTS_DIR is set and not empty else use our default directory
+# This will be used to point to the right kubernetes manifests.
+if [ -z ${CONTAINER_MANIFESTS_DIR+x} ]
+then
+    log "You must provide a CONTAINER_MANIFESTS_DIR, aborting"
+    exit 1
+fi
+
+ruby adapt_salt_config.rb $SALT_DIR > /dev/null
+
+for template in $(ls $CONTAINER_MANIFESTS_DIR/*.yaml)
+do
+    log "Processing template $template..."
+    cat $template | ruby process_manifest.rb $CONTAINER_MANIFESTS_DIR $(readlink -f $PWD/..) $SALT_DIR > manifests/$(basename $template)
+done
+
+default_interface=$(awk '$2 == 00000000 { print $1 }' /proc/net/route)
+ip_address=$(ip addr show $default_interface | awk '$1 == "inet" {print $2}' | cut -f1 -d/)
 
 for template in $(ls manifest-templates)
 do
-    log "Processing template $template..."
-    sed -e "s#\${project_dir}#$(dirname $PWD)#" \
-        -e "s#\${ip_address}#$ip_address#" \
-        -e "s#\${salt_dir}#$salt_dir#" manifest-templates/$template > manifests/$template
-done
-
-for template in $(find salt-templates -type f | cut -d'/' -f2-)
-do
-    log "Processing template $template..."
-    sed -e "s#\${project_dir}#$(dirname $PWD)#" \
-        -e "s#\${ip_address}#$ip_address#" \
-        -e "s#\${salt_dir}#$salt_dir#" salt-templates/$template > salt/$template
+    sed -e "s#\${ip_address}#$ip_address#" manifest-templates/$template > manifests/$template
 done
 
 if ! $(which kubelet >&/dev/null); then
@@ -70,6 +73,33 @@ fi
 # creates this file.
 sudo mkdir -p $PWD/tmp/mariadb-socket
 sudo chmod 777 $PWD/tmp/mariadb-socket
+
+set +e
+docker pull docker-testing-registry.suse.de/sles12/velum:development | grep "up to date" &> /dev/null
+image_up_to_date=$?
+set -e
+
+if [[ $image_up_to_date -ne 0 ]] ; then
+  log "New Velum image found on the registry"
+fi
+
+if [[ $image_up_to_date -eq 0 ]] && ( docker images | grep "^sles12/velum" &> /dev/null ) ; then
+  log "Velum development image is present and up to date"
+else
+  log "Building Velum development image..."
+  CONTAINER_BUILD=`docker run -v $(readlink -f $PWD/..):/srv/velum -d docker-testing-registry.suse.de/sles12/velum:development \
+                    bash -c "gem install --no-ri --no-rdoc --install-dir /var/lib/velum/ruby/2.1.0 bundler && \
+                    bundle config --local frozen 0 && \
+                    bundle config --local build.nokogiri --use-system-libraries && \
+                    bundle install --binstubs=/usr/local/bin --deployment --path=/var/lib/velum && \
+                    wget -q https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -P /opt && \
+                    tar -xjf /opt/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /opt && \
+                    mv /opt/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin && \
+                    rm -rf /opt/phantomjs-2.1.1-linux-x86_64"`
+  docker logs -f $CONTAINER_BUILD
+  docker commit $CONTAINER_BUILD sles12/velum:development
+  docker rm $CONTAINER_BUILD
+fi
 
 log "Launching kubelet"
 sudo kubelet --pod-manifest-path=$PWD/manifests --root-dir=$PWD/tmp --v=$KUBE_LOG_LEVEL --address=127.0.0.1 --hostname-override=127.0.0.1
